import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <ClerkProvider>

        <body className={inter.className}>
          <div className='mx-36 text-3xl'>
            
            <ClerkLoading>
              <div className='flex flex-col items-center min-h-screen'>
                Chargement en cour...
              </div>
            </ClerkLoading>

            <ClerkLoaded>
              <Navbar />
              <div className='flex flex-col items-center mt-10 min-h-screen bg-gray-900'>
                {children}
              </div>
            </ClerkLoaded>

          </div>
        </body>

      </ClerkProvider>

    </html>
  )
}
